name: Deploy

on:
  push:
    branches:
      - main # Ana dalınıza göre ayarlayın

jobs:
  deploy:
    runs-on: ubuntu-latest # İhtiyacınıza göre işletim sistemini değiştirin

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22' # Node.js sürümünü 22 olarak ayarlayın

    - name: Install dependencies
      run: npm install # Veya projeniz için uygun olan paket yöneticisini kullanın (yarn, pnpm vb.)

    - name: Build
      run: npm run build # Projenizin build komutunu ayarlayın

    - name: Deploy
      # Buraya dağıtım adımlarınızı ekleyin.
      # Örneğin, bir sunucuya SSH ile bağlanıp dosyaları kopyalayabilir,
      # bir bulut sağlayıcısının CLI aracını kullanabilir veya
      # özel bir dağıtım betiği çalıştırabilirsiniz.
      run: |
        echo "Dağıtım adımları buraya gelecek"
        # Örnek: scp -r build/* user@your-server:/var/www/html
